using UnityEngine;

public class GameManager : MonoBehaviour
{
    // Add any game management code here in the future
}

public class PlayerController : MonoBehaviour
{
    public float moveSpeed = 5f;
    public GameObject bulletPrefab;
    public Transform bulletSpawnPoint;

    void Update()
    {
        MovePlayer();
        if (Input.GetButtonDown("Fire1"))
        {
            Shoot();
        }
    }

    void MovePlayer()
    {
        float horizontal = Input.GetAxis("Horizontal");
        float vertical = Input.GetAxis("Vertical");
        Vector3 movement = new Vector3(horizontal, 0, vertical) * moveSpeed * Time.deltaTime;
        transform.Translate(movement);
    }

    void Shoot()
    {
        // Instantiate a bullet at the spawn point
        Instantiate(bulletPrefab, bulletSpawnPoint.position, bulletSpawnPoint.rotation);
    }
}

public class Bullet : MonoBehaviour
{
    public float speed = 20f;

    void Start()
    {
        Rigidbody rb = GetComponent<Rigidbody>();
        rb.velocity = transform.forward * speed; // Move the bullet forward
    }

    void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Enemy")) // Check if the bullet hits an enemy
        {
            Destroy(other.gameObject); // Destroy the enemy
            Destroy(gameObject); // Destroy the bullet
        }
        else if (other.CompareTag("Obstacle")) // Check if the bullet hits an obstacle
        {
            Destroy(gameObject); // Destroy the bullet
        }
    }
}
